packages:
  - .

overrides:
  '@wordpress/compose': 7.46.0
  '@wordpress/data': 10.46.0
  '@wordpress/element': 6.46.0
  '@wordpress/primitives': 4.46.0
  '@wordpress/rich-text': 7.46.0
  react: 18.3.1
  react-dom: 18.3.1

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  fs-ext-extra-prebuilt: true
  fsevents: true
  unrs-resolver: true
