"""Reviewed feature boundaries. Selectors locate evidence; they do not prove behavior."""
# Each topic: slug, symptom aliases, source selectors, expected contract, fixture/regression recipe.
C = {}
def add(repo,purpose,topics,dependencies=()):
 C[repo]={'purpose':purpose,'topics':[dict(zip(('id','symptoms','selectors','contract','qa'),t)) for t in topics], 'dependencies':list(dependencies)}
add('directorist-business-hours','Authors maintain business schedules; visitors see opening status and can filter open businesses.',[
 ('schedule','hours saving|overnight|timezone|open now|closed now|24 hours|business hour','business|hour|directory_types|csv','Schedule submission, timezone selection, disabled/24-hour states, overnight ranges, badges and open-now filtering are different paths. Compare the saved listing ID and timezone with the renderer and query clock.','Create schedules spanning midnight, a closed day and 24-hour day in two timezones. Save/reload in frontend and admin; compare detail badge and open-now results immediately before/after boundaries. Capture actual time and cache state.'),
 ('display-import','hours empty|hours not showing|hours missing|hours csv|hours badge|schedule import','csv|rest|widget|show_hours|template|directory','Single content widgets, card badges, REST response and CSV integration expose the schedule through separate contracts. A stored schedule alone does not prove any of those paths render.','Compare a no-plan listing and a plan allowing hours. Check native detail, card, REST and a builder template using the queried listing ID. Round-trip CSV on disposable listings and compare normalized schedule.')],['directorist-pricing-plans','directorist-divi-integration'])
add('directorist-pricing-plans','Sell per-listing or package entitlements and control listing features, renewal, expiry and subscription state.',[
 ('entitlements','no plan|missing fields|plan allowance|quota|plan assignment|pricing plans','FormFields|Feature|Restriction|Assignment|listing_type_manager|helper|Plan.php','Plan entitlements can suppress fields independently of saved listing metadata. Legacy post/meta plans and newer package tables are separate storage generations; select the actual implementation first.','Use two directory types, free/paid plans, exhausted and available quotas, and a listing with no assigned plan. Compare add/edit/detail rendering, assignment permission and package usage.'),
 ('checkout-renewal','renewal|expired listing|subscription|proration|cancel|trial|paid plan|package','Checkout|Payment|Subscription|Package|Renewal|Proration|Expiration|payments|subscription|data-controller','Checkout completion, recurring collection, package activation, listing renewal, cancellation and fallback plans must preserve distinct states. A paid order alone is not proof the correct package/listing was activated.','In a sandbox compare free, one-off, recurring and trial orders; duplicate webhook, failed renewal, cancel-at-period-end, expired listing renewal and plan change. Assert owner, order reference, package limits and dates.'),
 ('migration-admin','plan migration|legacy plan|plan sorting|missing package|pricing admin','Migration|Jobs|Admin|Setup|hooks|background|views','Migration/background repair and admin assignment can change plan relations and expiration. Keep migration status, legacy IDs and new IDs traceable; do not rerun destructive migration on client data.','Clone representative legacy plans/orders into disposable DB; capture counts and relations, migrate, retry interrupted batches, verify no duplicate packages and preserved lifetime/period dates.')],['directorist-stripe','directorist-paypal','directorist-authorize-net','directorist-coupon','directorist-claim-listing'])
add('directorist-woocommerce-pricing-plans','Use WooCommerce products, orders and optional subscriptions to sell Directorist listing packages.',[
 ('products-entitlements','woocommerce plan|wc plan|product plan|wc quota','wc-controller|controller|restriction|listing_type|helper','WooCommerce order/product identity drives listing entitlement. The plugin guards against simultaneous native Pricing Plans classes; verify which plan engine actually loaded.','Create a package product and two directory types; buy as a new author and assert listing quota, permitted fields and dashboard package. Test no purchase and exhausted quota.'),
 ('orders-subscriptions','woocommerce renewal|wc subscription|hpos|woocommerce checkout','subscription|payment|wc|direct-purchase|hooks','WooCommerce payment/status transitions and subscription repair belong to WooCommerce integration; do not route every payment issue to Directorist Stripe.','Use sandbox WooCommerce checkout; process completion, cancellation, renewal failure and retry. Compare HPOS setting, product/order IDs, listing expiry and package recovery without double activation.')],['directorist-claim-listing'])
add('directorist-claim-listing','Let a business owner request ownership, support approval/payment flows, and display verified status.',[
 ('claim-approval','claim listing|claim button|ownership|duplicate claim|claim approval','claim|helper|directory_type','Claim submission, duplicate detection, admin approval and author transfer are separate operations. A claimed badge is presentation evidence, not proof of ownership transfer.','Use an admin-owned listing, claimant and unrelated author. Submit, repeat, reject/approve; check claim record, actual post_author, permissions and outgoing email captured locally.'),
 ('paid-claim-badge','paid claim|claimed badge|verified badge|claim tooltip','claim|directory_type|helper','Claim pricing can use plan allowances or a manual charge; paid completion must reach the correct claim/listing. Badge content may be overridden by a builder/theme.','Compare free claim, plan-supported claim and manual fee; test failed/completed payment, card/detail tooltip and Divi badge. Preserve author ownership when only tooltip styling changes.')],['directorist-pricing-plans','directorist-woocommerce-pricing-plans','directorist-divi-integration'])
add('directorist-booking','Accept listing reservations, service appointments and events, with calendars, payments and owner management.',[
 ('availability','booking|reservation|appointment|time slots|guest confirmation|calendar','Database|Calender|MetaSubmission|FormBuilder|booking|helper','Availability calculation, slot capacity, guest confirmation and owner status changes are separate paths. Confirm the configured booking type before comparing dates or prices.','Create service slots and event capacity; attempt two guests for the last place, overlapping dates, timezone boundary and invalid confirmation. Inspect stored reservation/status and both customer/owner calendars.'),
 ('booking-payments','booking payment|booking refund|booking commission|wallet payout','Payment|Refund|Commission|Wallet','Booking payment uses booking-linked orders and may use WooCommerce. Commission, wallet, refunds and payout records must agree with booking status; an owner approval is not automatically a collected payment.','Test sandbox paid/failed booking, owner approval, cancellation, partial/full refund and commission/payout request. Assert booking/order references and balances; capture email without contacting users.')],['directorist-woocommerce-pricing-plans','directorist-pricing-plans'])
add('directorist-ai-search','Index listing content for semantic discovery and integrate ranked results into Directorist searches.',[
 ('indexing','ai search|semantic|indexing|api key|embedding','Index|Payload|Api|Settings|ListingService','Listing publication/meta/taxonomy changes schedule index/delete operations. Site identity, remote API provisioning and supported environment checks can prevent indexing before query interception runs.','Stub or use an authorized test API; publish/edit/unpublish a listing, change taxonomy and compare queued payload, index status, failure feedback and deletion. Do not send client data to a new service by default.'),
 ('ranked-results','irrelevant results|semantic ranking|ai fallback|ai autocomplete','QueryInterceptor|SearchContext|Candidate|Frontend|Universal','Semantic candidates are constrained by directory/filter context. Native fallback, score thresholds and Universal Search interception require independent checks.','Use two directories and restrictive category/price filters. Compare native, semantic success, empty response and API timeout; ensure excluded listings never leak through ranking.')],['directorist-universal-search'])
add('directorist-universal-search','Search across directory types using a dedicated search form and results route.',[
 ('cross-directory','universal search|all directories|cross directory search','UniversalSearch|Shortcode|DirectoristService|PageService|Settings','The extension owns cross-directory query/response and dedicated pages; Core still owns underlying listing/taxonomy data. AI interception may alter response ordering.','Create identically named listings in two directories with distinct taxonomy filters. Submit the universal form and verify result links, pagination, empty query and active directory state.'),
 ('builder-render','universal form missing|universal results|search preview','templates|views|Shortcode|resources','Shortcode and builder renderers must target the extension pages and load interactive assets. Editor placeholders are not frontend search results.','Compare shortcode, Divi form/result modules and frontend after save. Submit with keyboard, clear filters and revisit result URL directly.')],['directorist-ai-search','directorist-divi-integration'])
add('directorist-search-alert','Save a user search and send matching-listing notifications on configured schedules.',[
 ('saved-search','search alert|saved search|alert preferences','Ajax|Database|Dashboard|helper','Saved searches preserve filter values and ownership; create/edit/delete actions and expiration have different data paths.','Save keyword/category/location/custom filters as user A, edit and delete; ensure user B cannot operate A records. Reload dashboard and verify displayed filters match request.'),
 ('alert-delivery','search alert email|daily alert|weekly alert|monthly alert','Email|Settings|base','Listing publication and scheduled delivery select matches on immediate/daily/weekly/monthly paths. Cron execution and email capture must be proved separately.','Create matching and nonmatching listings after the save time. Run only relevant local cron events; assert recipient, schedule, no repeat notifications and expired-search cleanup.')])
add('directorist-analytics','Track listing engagement and present author/admin analytics and periodic reports.',[
 ('tracking-reports','analytics|weekly report|monthly report|duplicate last listing|view tracking','Report|Email|Analytics|Tracking|Statistics|Controller|Cron|Job','Use the selected implementation branch: default main is a scaffold and cannot explain the newer report flow. Track listing identity through aggregation and report loops.','Use at least three listings with different event counts and owners. Generate weekly/monthly reports locally, assert each listing appears once with its own totals and correct period.'),
 ('dashboard','analytics dashboard|chart|click count|report filter','resources|Provider|routes|Model|Repository','Dashboard query ranges, ownership and frontend charts are separate from report email formatting. Source features absent from a variant must be treated as absent, not assumed available.','Compare author and admin views, date ranges with no data and boundary events, timezone and listing filter; check network responses and rendered chart totals.')])
add('directorist-advanced-review','Support multi-criterion ratings, review replies, attachments, reactions and reports.',[
 ('review-data','advanced review|review criteria|rating average|review translation','Review|Settings|Comment|Snap','Review criteria and comments are linked records; activation/deactivation snapshots affect directory builder layouts. Core reviews and extension reviews must not be counted twice.','Create two criteria and unequal ratings, edit/delete a review, compare average, sorting and translated singular/plural text. Check activation snapshot restoration only in a disposable clone.'),
 ('moderation-media','review reply|review attachment|review reaction|report review','Reply|Attachment|Reaction|Report|Middleware|routes','Replies, upload deletion, reactions and abuse reports have distinct endpoints and authorization.','Use owner, reviewer, guest and unrelated account. Test permitted/forbidden edits, attachment type/size, duplicate reaction and report submission; compare API and rendered replies.')])
add('directorist-listing-import','Import listings from Google Places and feeds with mapping, duplicate checks and scheduled runs.',[
 ('google-import','google import|listing importer|place id|field mapping|import hours','google/','Google imports resolve directory fields, map source types, identify existing Place IDs, download images and optionally map hours/reviews. Mapping a value is not proof a dependent extension displays it.','Import a small authorized sample into a disposable directory. Repeat the same Place ID; check duplicates, field types, image IDs, hours and review averages. Test missing photo/API failure without corrupting existing data.'),
 ('feed-import','rss import|feed import|scheduled import|duplicate feed','includes/|admin/','Feed discovery, preview, feed configuration and scheduler are separate; duplicate detection must remain stable across scheduled retries.','Use a local test feed with unique IDs, updated item and malformed response. Preview, run twice, schedule once and check counts, mappings, logs and cleanup.')],['directorist-business-hours','directorist-gallery','directorist-advanced-review'])
add('directorist-notifications-pro','Deliver browser push notifications for listing/order events and user preferences.',[
 ('subscription','push notification|browser permission|service worker|vapid','web-push|rest-api|frontend|notification','Browser permission, service worker scope, authenticated subscription persistence and per-user preference are required before sending.','On HTTPS localhost/test origin use two users and browsers. Grant/deny permission, subscribe/unsubscribe and disable preference; verify endpoint ownership and service worker scope without publishing credentials.'),
 ('events-delivery','push duplicate|push missing|notification log','event-integration|sender|admin-log|settings','Legacy and new order hooks can describe the same event; completion deduplication and endpoint failure handling must avoid duplicate notifications.','Capture test pushes for listing publish/edit/expiry and paid order; replay completion hook, expire an endpoint and check logs/recipient preferences. Do not trigger real client notifications.')])
add('directorist-mpesa-payment-gateway','Collect M-Pesa payments with STK push and supported recurring schedules.',[
 ('checkout','mpesa|m-pesa|stk push|kenyan phone|kes','MPesa|MpesaApi|Settings|OAuth|CheckoutService','Phone normalization, KES amount rules, credentials and processor compatibility gate the request. A successful OAuth test does not prove checkout collection.','Use API stubs or authorized sandbox; test 01/07 phone formats, fractional amount rejection, missing credentials and unsupported currency; verify submitted amount/reference and checkout feedback.'),
 ('callback-recurring','ratiba|mpesa callback|mpesa renewal','MpesaService|Cron|CheckoutController|routes','Callbacks must resolve the correct order and handle repeat events; pending polling, initial package binding and recurring schedule mapping have separate paths.','Replay success/failure/duplicate callbacks for two orders; test pending query and supported/unsupported plan intervals, cancellation and receipt status. Assert no duplicate payment/package.')],['directorist-pricing-plans'])
add('directorist-stripe','Collect card/Stripe payments and synchronize checkout, webhooks and subscriptions with Directorist orders.',[
 ('checkout-tax','stripe|card payment|sepa|stripe tax|stripe coupon','Stripe.php|directorist-stripe.php|Settings|Checkout|helper','Legacy and processor generations differ. Amount currency conversion, tax, discounts and trial calculation must be traced to the installed generation; SEPA belongs to a specific branch.','Test sandbox zero-decimal and normal currencies, tax-inclusive/exclusive prices, coupon and trial. Inspect checkout total, order amount, redirect and delayed-payment state.'),
 ('webhooks','stripe webhook|stripe renewal|stripe cancellation','Webhook|Controller|Service|Provider|directorist-stripe.php','Browser success, webhook confirmation and subscription renewal are separate. Verify signature handling and order reference before altering completion logic.','Replay valid, invalid-signature, delayed, out-of-order and duplicate events in sandbox; assert payment, package dates and cancellation once, plus failed renewal.')],['directorist-pricing-plans','directorist-coupon'])
add('directorist-paypal','Collect PayPal payments and reconcile external confirmation with local orders.',[
 ('checkout','paypal|paypal checkout|paypal sandbox','paypal|MenuService|Gateway|Payment|helper','Legacy IPN and newer registered gateway implementations differ; inspect actual processor/service availability rather than assuming the newer header implies full support.','Use authorized sandbox, verify merchant/mode/currency/order return URL, abandon payment and return. Compare displayed receipt with actual stored order status.'),
 ('confirmation','paypal ipn|paypal webhook|paypal pending','IPN|paypal|Controller|routes|Gateway','IPN verification/transaction handling in the legacy implementation must bind to the correct order; a return URL alone is not payment proof.','Replay sandbox verified, forged and duplicate notifications, return before notification and failed notification. Check order amount, transaction identity and one-time completion.')],['directorist-pricing-plans'])
add('directorist-authorize-net','Connect Authorize.net checkout and confirmation to Directorist payment flows.',[
 ('hosted-checkout','authorize.net|authorize net|hosted payment|accept hosted','Authorize|Settings|Checkout|TwoCheckout|API','Legacy source retains 2Checkout-named internals despite the Authorize.net product. The newer processor contains hosted-payment and subscription paths; do not route by class name alone.','Inspect installed generation, sandbox credentials and hosted form request. Test approval, decline, cancel and invalid configuration; compare correct order reference and amount.'),
 ('recurring-webhook','authorize webhook|authorize subscription','Controller|Payment|routes|Settings','Newer webhook/subscription API code is separate from the legacy completion path. Branch header 999.0.0 is not a released-version assertion.','Use stubs/sandbox for initial payment, recurring transaction, duplicate event and cancel; check authenticated callback and subscription schedule without charging clients.')],['directorist-pricing-plans'])
add('directorist-coupon','Apply configured discounts to eligible checkout totals and track coupon usage.',[
 ('discount-rules','coupon|discount code|coupon expired|coupon limit','Coupon|Ajax|Helper|AdminCallbacks','Admin rules, AJAX eligibility, checkout calculation and usage count are separate. Stripe checkout adaptation does not establish discounts for every future renewal.','Create fixed/percentage coupons with expiry, usage limit and plan restrictions. Test eligible/ineligible plans, final allowed use, invalid code, tax and total floor.'),
 ('gateway-usage','stripe discount|coupon renewal|coupon uses','CouponHandler|coupon.php','Coupon application to Stripe session and local order items must agree; update usage only according to the actual hook lifecycle.','Complete and abandon sandbox checkout, replay completion and compare usage count/order receipt. Verify first invoice vs renewal behavior explicitly before promising recurring discounts.')],['directorist-stripe','directorist-pricing-plans','directorist-gamipress-integration'])
add('directorist-digital-marketplace','Sell listing-attached digital files through WooCommerce, with download access and vendor accounting.',[
 ('purchase-download','digital marketplace|download file|price tier|buy file','WooCommerce|Purchase|Listing|Tabs_Downloads','Listing files/tiers generate WooCommerce products/orders; authorized download access follows purchase state, not just a visible download button.','Create two file tiers and a nonbuyer. Buy one tier in sandbox, test authorized download, unpaid/cancelled order, changed file and refund revocation.'),
 ('vendor-wallet','vendor commission|digital payout|vendor balance','Payout|Wallet|WC_Helper|Order','Order/refund status updates vendor balances and payout records. Do not confuse a payout request with paid settlement.','Compare completed and refunded sales for two vendors, commission rates, repeated order-status events and payout request/admin decision; assert no cross-vendor data exposure.')])
add('directorist-job-manager','Add job-specific fields and accept applications with attachments and email delivery.',[
 ('job-fields','job manager|job salary|job deadline|open position','settings-manager|helper|templates|widget','Salary/type/position/deadline fields and search filters are separate from application submission. Directory builder placement determines visibility.','Create two job types and salary ranges; save/edit, filter and view in native/Divi detail. Check empty and expired deadline presentation.'),
 ('applications','job application|resume upload|apply now','form|file|mail|ajax|generate-pages','Application form generation, upload restrictions, cleanup and email construction form the submission pipeline.','Submit valid/invalid attachments and missing required fields as guest/user; capture mail locally, verify intended recipient, validation feedback and temporary file cleanup.')],['directorist-divi-integration'])
add('directorist-listings-with-map','Render synchronized map/listing views with filtering and AJAX navigation.',[
 ('map-query','listings with map|map pins|map sync|map pagination','Model|ajax|hooks|helper','AJAX query state and rendered listing IDs must agree with map markers, directory and taxonomy filters; map-service failures are not automatically query defects.','Use three geocoded listings across two directories; filter, change view, paginate and pan where supported. Compare visible IDs/markers and request parameters, including zero results.'),
 ('map-render','map blank|map layout|map clustering','templates|settings|assets|Model','Google/OpenStreetMap templates and asset loading depend on configured provider; keys, geolocation permission and script order affect rendered behavior.','Check both supported providers with authorized keys, denied geolocation and narrow viewport. Verify marker click/card focus and no stale pins after AJAX.')],['directorist-business-hours'])
add('directorist-announcement','Publish targeted announcements to directory users and their dashboards.',[
 ('publish-target','announcement|target users|announcement email','settings|content-update|helpers','Announcement post type, recipient selection, expiry and send action control visibility and email.','Create announcement for user A only and another for all users with expiry. Check A/B dashboard, captured email and expiry cleanup.'),
 ('read-state','unread announcement|announcement badge|dismiss announcement','frontend|content-update|helpers','Seen/dismissed state and new-count responses should be scoped to the current user.','Read/close as A, refresh badge and confirm B state unchanged. Test expired and deleted announcements.')])
add('directorist-adverts-manager','Place ads at configured Directorist page and listing-loop positions.',[
 ('ad-placement','ads manager|advertisement|ad placement','AdDisplayPages|AdsManagerCPT|AdminCallbacks|Helper','Page-specific placement hooks, in-loop positions and ad type selection control rendering. A configured slot requires the actual template to invoke its hook.','Create image/text ads; test all-listings and search-result loop positions with pagination, empty results and mobile. Compare selected page slots with rendered occurrences.'),
 ('ad-shortcode','ad shortcode|ad widget|ad styling','Shortcode|Widget|DynamicStyle|Enqueue','Shortcode/widget output and dynamic styles are separate from automatic page-hook insertion.','Place same ad through widget and shortcode in a test page; verify click destination, dimensions and no unintended duplicate automatic placement.')])
add('directorist-compare-listing','Let visitors select listings and compare their fields on a dedicated page.',[
 ('selection','compare listings|compare button|compare sidebar','Ajax|CompareButton|Helper','Selection add/remove, sidebar response and compare-page IDs must remain synchronized for guest and authenticated contexts.','Select two listings, remove one, refresh, clear and open comparison. Test repeated clicks and selection across pages.'),
 ('comparison','comparison table|compare page','Shortcode|Activate|Settings|templates','Comparison page/shortcode and directory field configuration determine which fields display.','Compare listings with missing and populated custom fields from one/two directories; check page setup, values, image output and mobile horizontal overflow.')])
add('directorist-directory-linking','Link a listing to other listings and expose linked-directory fields and search.',[
 ('link-selection','directory linking|linked listing|multi directory linking','Builder|base|templates','Selection stores listing IDs, while presentation resolves linked listings and their directory/review data. IDs and scalar/array representations require normalization.','Link multiple listings from another directory, edit/remove/reorder and reload. Test deleted/private target and empty selection.'),
 ('link-search','linked directory search|linked listing missing','Builder|base|Settings','Linked-directory search and single display must use the configured target directory and valid IDs.','Search by linked listing and compare native single output with Divi LinkDirectory; test two directory types and legacy serialized selection.')],['directorist-divi-integration'])
add('directorist-faqs','Add editable question/answer entries to listing forms and detail views.',[
 ('faq-edit','faq|question answer|faq saving','faqs|directory_type|helper','Frontend/admin FAQ submission and dynamic row actions must preserve question/answer pairing; plan restrictions can hide the field independently.','Create three distinct FAQs, delete middle row, reorder if supported, save/reopen and inspect values. Test author ownership, empty answer and markup escaping.'),
 ('faq-render','faq accordion|faq missing|faq widget','templates|widget|faqs|directory_type','Single content widget, shortcode and classic widget are separate render paths.','Compare native detail, shortcode/widget and Divi module for same listing; expand/collapse by keyboard and test no-plan vs allowed plan.')],['directorist-pricing-plans','directorist-divi-integration'])
add('directorist-gallery','Store listing image galleries, display them and import remote gallery attachments.',[
 ('gallery-edit','image gallery|gallery upload|gallery saving','bd-directorist-gallery|directory_type|templates','Upload, retained-image values and deselected-image cleanup must preserve images still attached to the listing.','Upload three images, remove one, save/edit again, test permissions and invalid files; compare attachment IDs and display settings.'),
 ('gallery-import','gallery cron|gallery import|gallery slider','importer|gallery|templates','CSV/gallery import scheduling and remote sideload are distinct from ordinary form uploads; cron schedule registration can affect execution.','Use two test image URLs plus failure; run relevant local import event twice, verify deduplication/status and gallery frontend. Inspect theme/builder image context separately.')],['directorist-pricing-plans','directorist-divi-integration'])
add('directorist-slider-carousel','Display queried listings in a slider/carousel using extension shortcode settings.',[
 ('slider-query','listings slider|carousel|slider listings|slider order','slider|template','Shortcode attributes select/order listings; this extension is different from Core listing-card image slides and client-specific daily sliders.','Create listings with distinct category/date/featured state, set shortcode filters/count and compare returned IDs and ordering.'),
 ('slider-motion','carousel arrows|slider responsive|autoplay','slider|assets|templates','Frontend assets and responsive settings determine carousel navigation/autoplay independently of the listing query.','Test desktop/mobile controls, keyboard/focus, one/zero results, multiple sliders and reduced-motion preference. Verify emitted options before changing global scripts.')])
add('directorist-mark-as-sold','Let listing authors mark listings sold and alter badges, price/contact visibility and queries.',[
 ('sold-state','mark as sold|sold button|sold badge','mark-as-sold','Dashboard action, stored sold state, badge and query exclusion are separate contracts; sold is not inherently WordPress trash/unpublish.','Toggle owned listing sold/available, attempt as another author; reload dashboard/detail/archive and verify expected visibility and stored state.'),
 ('sold-display','sold price|sold contact|hide sold','mark-as-sold','Price replacement, contact handling and author/archive query hooks can differ by setting.','Compare sold and unsold listings under hide/show settings; check author page, search, price and contact action without deleting either listing.')])
add('directorist-social-login','Authenticate/register users through configured Google/Facebook providers.',[
 ('provider-auth','social login|google login|facebook login|oauth','social-login|compatibility','Provider token verification precedes user registration/login. Callback/origin configuration and account mapping must be inspected; browser button appearance is not authentication proof.','Use test provider apps and accounts; verify valid/expired/forged token, existing email vs new account and redirect. Never log tokens or mutate production provider apps.'),
 ('login-ui','social button|google button missing|facebook button','template|assets|social-login','Settings, external SDK loading and login/registration compatibility affect button rendering.','Compare login/signup, blocked SDK and popup cancellation; keyboard activate and inspect network/console without exposing credentials.')])
add('directorist-google-recaptcha','Apply Google challenge/token validation to selected Directorist public forms.',[
 ('verification','recaptcha|captcha|spam protection|v3 score','recaptcha|directory_type|recaptchalib','v2/v3 branches differ. Server verification and per-form enable settings matter; client challenge success alone cannot authorize submission.','Test listing, registration, review and contact forms with valid, missing, expired and replayed tokens using test keys. Compare actual installed variant and server error.'),
 ('captcha-render','captcha missing|captcha badge|captcha key','recaptcha|assets|directory_type','Site/secret pairing, configured domains, form options and script loading control visible challenge/badge.','Render multiple protected forms, AJAX validation errors and disabled setting; verify no duplicate SDK load or hidden required challenge.')])
add('directorist-mailchimp','Subscribe consenting directory users or contacts to a configured Mailchimp audience.',[
 ('registration','mailchimp|newsletter signup|audience','registration|mailchimp|settings','Registration consent and audience configuration control subscription; successful WordPress registration does not guarantee Mailchimp success.','Use stub/test audience; register with/without consent, existing subscribed email and API failure. Check requested list and subscription state.'),
 ('contact-subscription','mailchimp contact|contact newsletter','listing-contact|mailchimp|settings','Contact-owner submission has its own subscription hook and consent path.','Submit contact with permitted consent settings; inspect locally captured mail and API request independently. Ensure failed contact validation does not falsely imply subscription.')])
add('directorist-gamipress-integration','Award points for Directorist activity and optionally redeem discount coupons.',[
 ('points','gamipress|points|achievement|reward','listeners|triggers|requirements|rules|author|dashboard','Listing/review/favorite/order events feed GamiPress rules; event occurrence and rule eligibility are separate.','Configure one rule each for publish/review/favorite, trigger and repeat, inspect points/log and unrelated user balance.'),
 ('redeem-coupon','redeem points|gamipress coupon','coupon-manager|settings|utils','Coupon redemption bridges GamiPress points and Directorist Coupon state; balance and coupon uses must stay consistent.','Redeem with sufficient/insufficient points, repeat request and use/expire coupon. Check both point deduction and coupon ownership/usage.')],['directorist-coupon'])
for repo,brand in [('directorist-buddypress-integration','BuddyPress'),('directorist-buddyboss-integration','BuddyBoss')]:
 add(repo,f'Expose Directorist listings in {brand} profiles, groups and activity.',[
 ('profile-groups',brand.lower()+'|profile listings|group listings','component|screens|group|functions|settings','Profile listing/favorite/add screens and group-connected IDs depend on the community platform and active components.','Use two users and public/private groups. Connect/disconnect listings, view profile tabs and attempt unauthorized group edits; check counts/pagination.'),
 ('activity',brand.lower()+' activity|share listing|listing timeline','activity|actions|builder|template','Publication/share events create activity entries; deletion/visibility and login redirects must respect community context.','Publish/share/delete a listing; compare timeline, group privacy and redirected login route. Ensure unrelated users do not receive private listing access.')])
add('directorist-live-chat','Provide listing-linked private conversations and dashboard chat history.',[
 ('conversation','live chat|chat history|message owner','live-chat|helper|directory_type','Listing restriction, participant identity and conversation lookup precede display. Native Live Chat is separate from HelpGent messaging.','Use listing owner, buyer and unrelated user. Start a conversation, refresh history, attempt another conversation ID and verify authorized visibility.'),
 ('socket-delivery','io is not defined|socket|chat messages not sending','assets|live-chat|helper','Socket dependency/loading and fallback handling vary by branch; history persistence and real-time delivery require separate proof.','Test connected socket, unavailable socket and refreshed history; compare browser errors and stored message identity. Use local test messages only.')],['directorist-pricing-plans','directorist-divi-integration'])
add('directorist-helpgent-integration','Expose scoped HelpGent forms, responses and contacts in Directorist user dashboards.',[
 ('forms-responses','helpgent|video message|audio message|lead form|response access','FormController|ResponseController|MenuService|Settings|helper|routes','HelpGent owns form/response entities; this integration scopes queries, quotas and dashboard permissions. Pro-only settings depend on the actual HelpGent edition.','Create forms as two listing authors, submit test response/media, then edit/read/archive as each user. Check quotas and unauthorized attachment access.'),
 ('contacts-notifications','helpgent contact|helpgent email|response notification','Contact|Summary|Tag|ListController|EmailNotification','Contacts, tags, summary counts, exports and email recipients use integration-specific query scopes.','Compare author A/B contacts/counts, tag edits/export and locally captured response email. Verify no cross-author response or media leakage.')])
add('directorist-divi-integration','Build native Divi directory layouts while preserving Directorist queries, fields and actions.',[
 ('search-archive','divi search|divi listings|divi filter|divi pagination','HomepageSearch|SearchForm|Archive|Pagination|CategoryHierarchy','Search composition, directory state and AJAX archive requests must retain the same filter contract across editor and frontend.','Use two directories with different fields, compose search/results, filter/sort/paginate and direct-open URL. Compare editor attributes, request parameters and rendered IDs.'),
 ('single-modules','divi|divi business hours|divi badge|divi field','DiviModules|ListingsController|ModuleDependency|ModuleUtil|DirectoristHelper','Extension modules depend on installed plugin basenames and queried listing context. Theme Builder body-layout ID must not replace actual listing ID.','Render Business Hours, Claim, FAQ and a custom field for two listings via Theme Builder. Compare editor preview vs frontend and unavailable dependency notice without deactivating client plugins.'),
 ('templates-import','divi template|divi import|divi conditions|author profile','ThemeBuilder|TemplateLibrary|CustomSingle|AuthorProfile','Theme Builder conditions, template library imports and author context have distinct persistence/remapping paths. Import permission is not implied by reading a template.','In disposable clone import a small approved package; verify ID/media remaps, directory conditions and author route. Check previous content retained and native editing after save.')],['directorist-business-hours','directorist-claim-listing','directorist-faqs','directorist-gallery','directorist-booking','directorist-universal-search','directorist-pricing-plans'])
add('addonskit-for-bricks','Provide native Bricks elements and dynamic Directorist data tags.',[
 ('elements','bricks|addonskit for bricks|bricks search','Elements|Plugin|Support','Element controls convert to Directorist shortcode/query settings; Core owns resulting listing workflows. Dependency checks require actual Bricks and Directorist.','Build search, listings, add-listing and checkout elements in a local Bricks page; save/reopen and exercise native search/submission.'),
 ('dynamic-tags','bricks dynamic|bricks field|bricks category image','DynamicTags|Support','Dynamic field/tag values depend on listing/directory/taxonomy context; editor sample is not final queried object.','Use two directories with same custom field type, category images and empty values. Compare loop/detail/editor output and escaped field values.')])
add('directorist-oxygen-integration','Connect Directorist workflows to Oxygen elements and controls.',[
 ('elements','oxygen|oxygen 6|oxygen element','element|control|integration|src|includes','The Oxygen 6 branch can differ substantially from legacy shortcode elements. Identify the actual integration files and Oxygen generation before changing controls.','Build listings/search/detail in the installed Oxygen generation; save/reopen and compare filter IDs, pagination and native form behavior.'),
 ('render-assets','oxygen blank|oxygen shortcode|oxygen scripts','element|integration|assets|src|includes','Element rendering and relaxed shortcode asset restrictions determine whether interactive Directorist scripts load.','Compare editor and frontend on add-listing, checkout and search pages; test AJAX validation, map/script load and no duplicate initialization.')])
add('directorist-wpml-integration','Translate Directorist listing, directory and taxonomy contexts through WPML.',[
 ('translation','wpml|translation|multilingual|language switch','Translate|Translation|WPML|Taxonomy|Listing|Directory|app.php','Language IDs, directory builder data and translated taxonomy/listing relationships require WPML-aware mapping; translating page text alone does not translate listing configuration.','Create two languages, two directories and translated listing/category pairs; switch language on add/edit/detail/search and compare object IDs and labels.'),
 ('queries-links','translated listing missing|wpml search|wpml url|wpml page','Query|Permalink|Page|Search|Filter|Helper|app.php','Translated page links and language-filtered queries can differ from the default language and cached results.','Search a translated listing, follow pagination and dashboard/add-listing links, then switch language. Verify current-language term IDs, URLs and no unintended cross-language results.')])
# Additional feature boundaries discovered in newer implementation files, not defaults.
def topic(repo,tid,symptoms,selectors,contract,qa):
 C[repo]['topics'].append(dict(zip(('id','symptoms','selectors','contract','qa'),(tid,symptoms,selectors,contract,qa))))
topic('directorist-booking','calendar-dashboard','google calendar|booking oauth|calendar conflict|booking dashboard','GoogleCalendar|Dashboard|BookingController|Widget|CustomPage','The newer branch adds Google Calendar OAuth/settings, event insertion/deletion and conflict checks, plus owner/customer dashboard filters. This is distinct from local slot availability.','Use a test calendar with authorized credentials, connect/disconnect and create/cancel a booking. Check conflict behavior, calendar IDs, event deletion and filtered owner/customer counts. Keep OAuth tokens out of evidence.')
topic('directorist-analytics','privacy-export','analytics privacy|do not track|dnt|anonymize ip|analytics export|raw logs','Privacy|Activity|AuthorLogin|Stats|Export|SettingsController','Tracking respects configured privacy/admin/DNT/IP/referrer settings; raw log retention, aggregation and CSV export are distinct operations. Deleting raw logs does not necessarily delete aggregates.','Use DNT on/off, admin vs author and query-string referrers in a local fixture. Compare raw/aggregate counts, anonymization, date range export and authorized cleanup; do not export client personal data without scope.')
topic('directorist-wpml-integration','string-packages','wpml labels|wpml builder|wpml settings|ate|string translation|translated shortcode','String_Package|UI_Translation|Translation_Management|Settings|Asset','Directory-builder and page/shortcode/block/Elementor UI strings are registered/synchronized through WPML package workflows. Completed ATE translations and runtime fallback strings have separate readers/writers.','Translate directory field labels and native page controls via a completed test translation job, save source again and verify update flags, translated frontend/editor labels and unchanged translated object relationships.')
topic('directorist-advanced-review','builder-migration','review migration|review activation|review layout','Migration|Snap|FrontendServiceProvider','Activation/deactivation snapshots preserve builder review-section layouts while extension tables store criteria/reactions. Restoring a layout is distinct from migrating review data.','On a disposable clone capture builder meta and reviews, activate/deactivate and compare snapshots/restored layout. Validate no data loss or duplicate review section after repeated activation.')
# Route frontend implementations and their actual repositories into existing feature topics.
EXTRA={
 'directorist-divi-integration':{'single-modules':'Visual-Builder|directorist-divi-integration.php'},
 'directorist-universal-search':{'cross-directory':'Repository|helper|Activation'},
 'directorist-notifications-pro':{'subscription':'service-worker'},
 'directorist-analytics':{'tracking-reports':'Stats|Activity|AuthorLogin'},
 'directorist-advanced-review':{'moderation-media':'resources/js'},
 'directorist-ai-search':{'indexing':'Core/|DirectoristAccount|DirectoristDependency|AdminMenu'},
 'directorist-search-alert':{'saved-search':'assets/js|Enqueue'},
 'directorist-woocommerce-pricing-plans':{'products-entitlements':'validator|ajax|views|woo-admin|assets/js'},
 'directorist-paypal':{'checkout':'SettingsService|DirectoristService|CheckoutService|Paypal|PayPal'},
 'directorist-pricing-plans':{'entitlements':'PlanController|ListingsController|app/DTO/Plan/|app/Enums/Plan/','checkout-renewal':'PlanOrderMeta|Order/|Mail/'},
 'directorist-digital-marketplace':{'purchase-download':'Admin/Builder|Core/Form|Core/Asset'},
 'directorist-job-manager':{'job-fields':'class-scripts'},
 'directorist-faqs':{'faq-edit':'assets/js/(admin-main|main)'},
 'directorist-adverts-manager':{'ad-placement':'assets/admin/js'},
 'directorist-live-chat':{'conversation':'admin-chat'},
 'directorist-helpgent-integration':{'forms-responses':'resources/js|Middleware'},
 'directorist-mpesa-payment-gateway':{'checkout':'DirectoristServiceProvider'},
}
for repo,topics in EXTRA.items():
 for t in C[repo]['topics']:
  if t['id'] in topics:t['selectors']+='|'+topics[t['id']]
topic('directorist-divi-integration','taxonomy-pricing-author','divi categories|divi locations|divi pricing plans|divi author profile','AllCategories|AllLocations|DirectoryTypes|PricingPlansController|PricingPlan|AuthorProfile|all-categories|all-locations|pricing-plans|directory-types','Taxonomy loops, plan-card composition and author profiles use different object contexts and controllers. Plan action buttons must retain native entitlements/checkout; taxonomy card IDs must not be listing IDs.','Use two categories/locations, two plan types and two authors. Compare counts, term links, plan price/features/action URL and author privacy in editor/frontend. Save/reopen modules and verify native destination flow.')
topic('directorist-pricing-plans','plan-presentation','pricing table|plan card|plan tabs|plan button|plan display','Shortcode|frontend/plans|PlanRepository|PlanAppConfiguration|badge.tsx|frontend/icons|View.php','Public plan presentation filters published/hidden plans and renders plan actions, pricing and features from repository/configuration data. Presentation must not grant package entitlement.','Create published, hidden and draft plans with different intervals; compare native plan list, price/tax/feature labels and selected-plan checkout link. Test logged-out, existing package and trial-ineligible users.')
MORE={
 'directorist-divi-integration':{'search-archive':'ListingsQueryHelper|DiviListings|listing-loop|RoutePruner','single-modules':'DiviModuleHelper|ListingCardImageSliderHelper|ListingsDiviContext|SanitizationHelper|DiviEnqueue|Traits/|Utils/Props|resources/js/(business-hours|gallery-extension|listings-favorite|helper|divi/)|routes/','templates-import':'template-import-admin'},
 'directorist-pricing-plans':{'entitlements':'ExtensionService|SettingsService|listing-owner-dashboard','migration-admin':'LegacyPlanApi|Queue|routes/'},
 'directorist-announcement':{'publish-target':'assets/js/admin'},
 'directorist-booking':{'availability':'MenuServiceProvider|routes/'},
 'directorist-gamipress-integration':{'points':'class-assets'},
 'directorist-authorize-net':{'hosted-checkout':'DirectoristServiceProvider'},
 'directorist-adverts-manager':{'ad-placement':'CustomWpListTable|ExtensionSettings'},
 'directorist-coupon':{'discount-rules':'CustomWpListTable'},
 'directorist-stripe':{'checkout-tax':'resources/js/index|routes/'},
}
for repo,topics in MORE.items():
 for t in C[repo]['topics']:
  if t['id'] in topics:t['selectors']+='|'+topics[t['id']]
BOUNDARIES={
 'directorist-divi-integration':{'single-modules':'modules/Modules.php'},
 'directorist-advanced-review':{'review-data':'resources/views/(create|filter|header|pagination)|components/(action|listing-owner|stars)','moderation-media':'delete-modal|login-alert|upload.php|views/replies'},
 'directorist-search-alert':{'saved-search':'admin/js|editing-form|search-result.php'},
 'directorist-announcement':{'read-state':'assets/js/main|template-parts/list'},
 'directorist-digital-marketplace':{'purchase-download':'assets/src/js/admin/main|templates/dashboard/downloads'},
 'directorist-booking':{'availability':'resources/js/(admin|common)/index|check-in-out|number-of-guest','calendar-dashboard':'google-calendar-modal.php'},
 'directorist-woocommerce-pricing-plans':{'products-entitlements':'templates/'},
 'directorist-pricing-plans':{'plan-presentation':'plan-app-configurations'},
 'directorist-gamipress-integration':{'points':'admin-script.js','redeem-coupon':'assets/js/script.js'},
 'directorist-directory-linking':{'link-selection':'admin/js|assets/js/main'},
 'directorist-buddypress-integration':{'activity':'assets/js/main'},
 'directorist-buddyboss-integration':{'activity':'assets/js/main'},
 'directorist-adverts-manager':{'ad-placement':'swbdpam-frontend'},
 'directorist-compare-listing':{'selection':'select-window|selected-listings-sidebar|atdlc-admin','comparison':'compare-page'},
 'directorist-live-chat':{'conversation':'templates/chat.php|templates/live_chat.php'},
 'directorist-mark-as-sold':{'sold-state':'assets/(admin|public)/js/main'},
 'directorist-gallery':{'gallery-edit':'admin/assets/js/main','gallery-import':'public/assets/js/main'},
 'directorist-claim-listing':{'claim-approval':'assets/js/main|class-db.php|admin-meta-fields','paid-claim-badge':'verified-badge|plan-selector'},
}
for repo,topics in BOUNDARIES.items():
 for t in C[repo]['topics']:
  if t['id'] in topics:t['selectors']+='|'+topics[t['id']]
