<?php
$searchform->price_range_template();
$searchform->rating_template();
$searchform->radius_search_template();
$searchform->open_now_template();
$searchform->tag_template();
$searchform->custom_fields_template();
$searchform->information_template();
$searchform->buttons_template();